
server:
  port: 8082

#redis
#spring:
#  redis:
#    # Redis服务器地址  
#    host: 
#    # Redis服务器连接端口  
#    port: 0
#    # Redis服务器连接密码（默认为空）
#    password: 
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 64
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）  
#        max-idle: 32
#        # 连接池中的最大空闲连接 
#        min-idle: 8
#        # 连接池中的最小空闲连接 
#        max-wait: -1ms
#        # 连接超时时间（毫秒） 
#    timeout: 1000ms
#      


logging:
  config: classpath:log4j2.xml

  